### ISSUE TITLE
Packaging an InfoType

### ISSUE THREAD

**Issue by Mantis-Ranson** [enebular/docs#158]
https://bitbucket.org/technicalrockstars/enebular-product-backlog/issues/326/infomotion-docs-packaging-an-infotype

New fixes in InfoMotionTool.md

**InfoType dependancies**

Each graph has it's own dependancies. To install them you will have to use npm install. Once installed you can continue on to pacaking and running the graph.

    cd [graph name]
    npm install
    Check the InfoTypes read.me for more details.

**Packaging**
    Packaging is needed when
    - A graph is created (eit create)
    - Before uploading a graph to Enebular

**Comment by tkymeno2** [comment]
マージされたので閉じます。
