### ISSUE TITLE
自動デプロイ(Circle CI 2.0)対応

### ISSUE THREAD

**Issue by daisuke-arakawa-uhuru** [enebular/docs#222]
Circle CI -> Netlifyの連携がCircle CI ver1サポート終了に伴い自動デプロイが止まってしまっているため、自動デプロイができるよう対応する

**Comment by daisuke-arakawa-uhuru** [comment]
一旦テスト用のブランチで自動化対応し、デプロイ確認できたので
他のブランチにも開放するよう設定ファイルを修正します。

**Comment by k-harada413** [comment]
#226 にて実装を行いました。closeにします。
