### ISSUE TITLE
英語のページに日本語を含むスクリーンショットがある

### ISSUE THREAD

**Issue by chris-sporelab** [enebular/docs#26]
英語のページに日本語を含むスクリーンショットがあって、英語の読者に悪い印象を与える可能性が高いです。 英語のドキュメントに日本語を全く含まないようにした方がいいです。

**Comment by k-harada413** [comment]
getting startedやINFOMOTION->Create Data SourceのページのINFOMOTION作成における、各項目説明は言語設定を英語にしても日本語が表示されてました。

milkcocoaはそもそも英語用ドキュメントが用意されていません。

Deploy内の下記スクリーンショットを差し替えます。
* mbed Cloud
* AWS IoT
* AWS Lambda

**Comment by kiyopikko** [comment]
> まだ以下の部分に日本語が残っています。
> 
> * milkcocoa系・・・元々英語表示するページが用意されていない
> * infotype・・・デフォルト言語を英語に切り替えても日本語で表示されていたので、英語未実装と判断
> * AWSLambda・・・まだ英語テキストが用意されていない

**Comment by tkymeno2** [comment]
レビューしました。

DEPLOYS > Example: mbed Cloudのページに画像のリンク切れがあります。

https://enebular-docs.netlify.com/en/_asset/images/Deploy/DeployFlow/AWSIoT/deploy-deployflow-awsiot_35.pngの画像ファイルがリンク切れになっているようです。

**Comment by k-harada413** [comment]
目野さんの指摘を反映し、プルリクをだしました。

**Comment by k-harada413** [comment]
該当プルリクエストがマージされたためcloseにします
