### ISSUE TITLE
adding "mbed cloud"

### ISSUE THREAD

**Issue by k-harada413** [enebular/docs#4]
## 概要
Deploy の中のmbed cloudページが現在未着手であるので、完成させる。

## DoD
該当ページのレビューをし、masterにマージされていること。

**Comment by k-harada413** [comment]
develop-dpd ブランチで作業します。

**Comment by k-harada413** [comment]
pull request #6 
自動テストのところでこけてしまいました。

**Comment by kiyopikko** [comment]
@k-harada413 
絶対こけるようになっていますので大丈夫です！

**Comment by k-harada413** [comment]
#6 宇佐美さんの指摘事項修正しました。

**Comment by kiyopikko** [comment]
@k-harada413 
こちら、chris さんが「まだ途中？」って言ってたのって
enebular-runtime-agent のインストールとかセットアップ手順がないからですね。
こちらは更新する予定はありますか...？

**Comment by k-harada413** [comment]
@kiyopikko mbedcloudのところは、enebular-runtime-agentのセットアップが終わっている前提で書いたので、本項目は今の範囲で大丈夫です。

別途、enebular-runtime-agent セットアップのページを作成しなければならないと思うので、月曜日ディスカッションしましょう

**Comment by k-harada413** [comment]
こちらのissue、closedにして大丈夫ですかね？

**Comment by kiyopikko** [comment]
了解です。大丈夫ですー

**Comment by k-harada413** [comment]
master に「mbed cloud ページ」がマージされたのでこちら Closed にします。
