### ISSUE TITLE
ドキュメントで"データフロー"を"データプロー"と誤記している

### ISSUE THREAD

**Issue by kiyopikko** [enebular/docs#77]
https://docs.enebular.com/ja/GetStarted/

```
データプローのデプロイが完了したら、データの可視化をしましょう。
```

## User Story

https://bitbucket.org/technicalrockstars/enebular-product-backlog/issues/206/-------------------------------

**Comment by tkymeno2** [comment]
pull request #93を行いました。

**Comment by k-harada413** [comment]
プルリクがdevelopブランチにマージされ問題が解決されたので、イシューを閉じました。
