### ISSUE TITLE
ログの仕様を明記する

### ISSUE THREAD

**Issue by kiyopikko** [enebular/docs#78]
- Node-REDがコンソール（stdout/err）に出力するログはNode-REDの設定やノードの設定によります。debugノードの出力がコンソール（stdout/err）に出力されるかどうかもdebugノードの設定次第になりますね。
- enebular-agentはNode-REDがstdout/errに出力するログを必ず全てキャプチャーします。
- enebular-agentがNode-REDからキャプチャーしたログ内容は、現在全て `info` のログレベルとして再ロギングします。
- enebular-agentがデフォルトで `info` レベルのログしか出力しませんが、環境変数で `debug` レベルのメッセージも出力するように出来ます。
- enebular-agentがモニタリングがONの場合にログをagent-managerにアップするので、enebular.comで確認出来ます。
- enebular-agentがデフォルトでコンソール（stdout/err）にログを出力しませんが、環境変数で出力するように出来ます。

## User Story

https://bitbucket.org/technicalrockstars/enebular-product-backlog/issues/209/task

**Comment by k-harada413** [comment]
#121 で該当項目がproductionにマージされていることを確認しました。
