### ISSUE TITLE
Make Japanese document of License Manager

### ISSUE THREAD

**Issue by tkymeno2** [enebular/docs#88]
- License Managerに関する日本語ドキュメントが存在しないため作成する必要があります。

ユーザーストーリー
https://bitbucket.org/technicalrockstars/enebular-product-backlog/issues/55/enebular-docs-enebular

**Comment by tkymeno2** [comment]
pull request #89 を行いました。

**Comment by k-harada413** [comment]
#89 のマージを確認したのでイシューを閉じます。
