### ISSUE TITLE
Pixelate image of API key name of MBED Cloud

### ISSUE THREAD

**Issue by tkymeno2** [enebular/docs#90]
docs/ja/_asset/images/Deploy/DeployFlow/mbed/deploy-deployflow-mbed_12.pngの画像にfor_intel_nic等、のキー名が使用されており、uhuruが取引していることが悟られる恐れがありよくない。

モザイクをかけたほうが良い。

**Comment by k-harada413** [comment]
上記イシューで対応しています。

**Comment by tkymeno2** [comment]
確認しました。
