### ISSUE TITLE
Be clearly written about flow-size able to deploy

### ISSUE THREAD

**Issue by tkymeno2** [enebular/docs#91]
デプロイ可能な最大のフローサイズについての記載がないため記載を行う必要があります。

**Comment by tkymeno2** [comment]
https://github.com/enebular/docs/blob/master/en/Deploy/index.md

ここに記載があるといいと思います。

**Comment by tkymeno2** [comment]
pull request #92を行いました。

**Comment by k-harada413** [comment]
#92 にて問題解決し、developブランチにマージされたのを確認しましたので、イシューを閉じます。
